all: trie trie2 trie3 trie4 trie5 trie6

trie: trie.c
	gcc -o trie trie.c -Wall -g

trie2: trie2.c
	gcc -o trie2 trie2.c -Wall -g

trie3: trie3.c
	gcc -o trie3 trie3.c -Wall -g

trie4: trie4.c
	gcc -o trie4 trie4.c -Wall -g -pthread

trie5: trie5.c
	gcc -o trie5 trie5.c -Wall -g -pthread

trie6: trie6.c
	gcc -o trie6 trie6.c -Wall -g
clean:
	rm -f trie2 trie3 trie4 trie5 trie6 *.o

